Eis a árvore de diretórios do projeto:

(dddap_at2) (base) zerocopia@zsgb3-ultra:~/flash_disk/infnet_community/dddap/at_2$ tree
.
├── app
│   ├── __init__py
│   ├── __pycache__
│   │   └── app.cpython-311.pyc
│   └── app.py
├── chat
├── data
│   └── conhecimentos.csv
├── docs
│   └── README.md
├── environment.yml
├── requirements.txt
├── src
│   ├── __pycache__
│   │   └── __init__.cpython-311.pyc
│   ├── main.py
│   └── utils
│       ├── __init__.py
│       ├── __pycache__
│       │   ├── __init__.cpython-311.pyc
│       │   └── utils.cpython-311.pyc
│       ├── utils.py
│       └── ver_partidas.py
└── tests
    ├── __init__.py
    └── test_utils.py

10 directories, 17 files

Eis o conteúdo do app.app.py:

import streamlit as st
from src.utils import get_match_data, write_to_file

match_ids = [12345, 67890, 11111]

st.title("Seleção de Partida")
selected_match_id = st.selectbox("Selecione o ID da partida:", match_ids)

if st.button("Obter Dados da Partida"):
    data = get_match_data(selected_match_id)
    st.write(data)
    write_to_file('partida_data.txt', str(data))

Eis o conteúdo do src.utils.utils.py:

from statsbombpy import sb

def get_match_data(match_id):
    match_data = sb.events(match_id=match_id, fmt='dict')
    return match_data


def write_to_file(filename, data):
    try:
        with open(filename, 'a') as file:
            file.write(data + '\n')
        print(f"Dados adicionados com sucesso ao arquivo {filename}!")
    except Exception as e:
        print(f"Erro ao adicionar dados ao arquivo {filename}: {e}")

Eis o conteúdo do src.main.py:

from src.utils.utils import get_match_data

match_id = 12345 
data = get_match_data(match_id)
print(data)


Eis o erro quando execucuto streamlit run app/app.py:

(dddap_at2) zerocopia@zsgb3-ultra:~/flash_disk/infnet_community/dddap/at_2$ streamlit run app/app.py 

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.17.70.210:8501

gio: http://localhost:8501: Failed to find default application for content type ‘text/html’
2024-12-12 14:00:50.915 Uncaught app execution
Traceback (most recent call last):
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/zerocopia/flash_disk/infnet_community/dddap/at_2/app/app.py", line 2, in <module>
    from src.utils.utils import get_match_data
  File "/home/zerocopia/flash_disk/infnet_community/dddap/at_2/src/utils/utils.py", line 1, in <module>
    from statsbombpy.sb import SB
ImportError: cannot import name 'SB' from 'statsbombpy.sb' (/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/sb.py)
/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
2024-12-12 14:04:58.503 Uncaught app execution
Traceback (most recent call last):
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/zerocopia/flash_disk/infnet_community/dddap/at_2/app/app.py", line 10, in <module>
    data = get_match_data(selected_match_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerocopia/flash_disk/infnet_community/dddap/at_2/src/utils/utils.py", line 4, in get_match_data
    match_data = sb.events(match_id=match_id, fmt='dict')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/sb.py", line 104, in events
    events = public.events(match_id)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/public.py", line 38, in events
    events = get_response(path)
             ^^^^^^^^^^^^^^^^^^
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/public.py", line 9, in get_response
    response.raise_for_status()
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/12345.json
2024-12-12 14:16:51.967 Uncaught app execution
Traceback (most recent call last):
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/home/zerocopia/flash_disk/infnet_community/dddap/at_2/app/app.py", line 10, in <module>
    data = get_match_data(selected_match_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerocopia/flash_disk/infnet_community/dddap/at_2/src/utils/utils.py", line 4, in get_match_data
    match_data = sb.events(match_id=match_id, fmt='dict')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/sb.py", line 104, in events
    events = public.events(match_id)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/public.py", line 38, in events
    events = get_response(path)
             ^^^^^^^^^^^^^^^^^^
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/public.py", line 9, in get_response
    response.raise_for_status()
  File "/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/statsbomb/open-data/master/data/events/12345.json
^C  Stopping...
(dddap_at2) zerocopia@zsgb3-ultra:~/flash_disk/infnet_community/dddap/at_2$ python src/utils/ver_partidas.py 
/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
    competition_id  season_id   country_name  ...           match_updated_360         match_available_360             match_available
0                9        281        Germany  ...  2024-07-15T14:17:00.877356  2024-07-15T14:17:00.877356  2024-07-15T14:15:54.671676
1                9         27        Germany  ...                        None                        None  2024-05-19T11:11:14.192381
2             1267        107         Africa  ...                        None                        None  2024-06-13T07:51:02.452825
3               16          4         Europe  ...     2021-06-13T16:17:31.694                        None  2024-06-12T07:44:38.559714
4               16          1         Europe  ...     2021-06-13T16:17:31.694                        None  2024-02-13T02:35:28.134882
..             ...        ...            ...  ...                         ...                         ...                         ...
69              55         43         Europe  ...  2024-04-16T12:47:18.505110  2024-04-16T12:47:18.505110  2024-04-16T12:44:40.558402
70              35         75         Europe  ...     2021-06-13T16:17:31.694                        None  2024-02-12T14:45:05.702250
71              53        106         Europe  ...  2024-02-13T13:30:52.820588  2024-02-13T13:30:52.820588  2024-02-13T13:27:17.178263
72              72        107  International  ...  2024-07-14T17:01:38.887279  2024-07-14T17:01:38.887279  2024-07-14T16:59:48.469596
73              72         30  International  ...     2021-06-13T16:17:31.694                        None  2024-02-13T09:41:26.379767

[74 rows x 12 columns]
/home/zerocopia/anaconda3/envs/dddap_at2/lib/python3.11/site-packages/statsbombpy/api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
     match_id  match_date      kick_off              competition  ...        away_managers data_version shot_fidelity_version  xy_fidelity_version
0     3890561  2016-05-14  15:30:00.000  Germany - 1. Bundesliga  ...  André Breitenreiter        1.1.0                     2                    2
1     3890505  2016-04-02  15:30:00.000  Germany - 1. Bundesliga  ...           Niko Kovač        1.1.0                     2                    2
2     3890511  2016-04-08  20:30:00.000  Germany - 1. Bundesliga  ...       Daniel Stendel        1.1.0                     2                    2
3     3890515  2016-04-09  15:30:00.000  Germany - 1. Bundesliga  ...        Dirk Schuster        1.1.0                     2                    2
4     3890411  2015-12-20  16:30:00.000  Germany - 1. Bundesliga  ...       Martin Schmidt        1.1.0                     2                    2
..        ...         ...           ...                      ...  ...                  ...          ...                   ...                  ...
301   3890263  2015-08-15  15:30:00.000  Germany - 1. Bundesliga  ...     Ralph Hasenhüttl        1.1.0                     2                    2
302   3890262  2015-08-15  15:30:00.000  Germany - 1. Bundesliga  ...    Michael Frontzeck        1.1.0                     2                    2
303   3890261  2015-08-15  18:30:00.000  Germany - 1. Bundesliga  ...         Lucien Favre        1.1.0                     2                    2
304   3890260  2015-08-15  15:30:00.000  Germany - 1. Bundesliga  ...        Markus Gisdol        1.1.0                     2                    2
305   3890259  2015-08-14  20:30:00.000  Germany - 1. Bundesliga  ...       Bruno Labbadia        1.1.0                     2                    2

[306 rows x 22 columns]
(dddap_at2) zerocopia@zsgb3-ultra:~/flash_disk/infnet_community/dddap/at_2$ 